invenio_pidstore/admin.py
setup.py

Adds a category icon for the sidebar menu in the new admin UI.

pidstore: category icon for admin UI

---

invenio_pidstore/upgrades/pidstore_2014_08_22_initial.py

* FIX: import of invenio_upgrader
Signed-off-by: Eamonn Maguire eamonnmag@gmail.com

global: fix import of invenio_upgrader

---

CHANGES.rst
MANIFEST.in
RELEASE-NOTES.rst
invenio_pidstore/translations/es/LC_MESSAGES/messages.po
invenio_pidstore/translations/fr/LC_MESSAGES/messages.po
invenio_pidstore/translations/invenio.pot
invenio_pidstore/version.py
setup.cfg

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

Invenio-PIDStore v0.1.1

---

invenio_pidstore/models.py

* FIX Uses nested transactions instead of sub-transactions.
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

models: nested transactions usage

---

invenio_pidstore/admin.py
invenio_pidstore/models.py
invenio_pidstore/provider.py
requirements-devel.txt
setup.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

installation: fix invenio_utils imports

---

.travis.invenio.cfg
.travis.yml
CHANGES.rst
MANIFEST.in
RELEASE-NOTES.rst
invenio_pidstore/__init__.py
invenio_pidstore/models.py
invenio_pidstore/version.py
setup.py

Invenio-PIDStore v0.1.2

---

invenio_pidstore/config.py

Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

providers: optional datacite provider

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

Invenio-PIDStore v0.1.3

---

setup.py

* Added missing entry points to invenio_db and invenio_base

setup: added entry_points

---

.travis.yml
setup.py

* Fixes database dependencies to depend on Invenio-DB. (closes #25)

installation: invenio-db extra dependencies

---

docs/api.rst
invenio_pidstore/cli.py
invenio_pidstore/ext.py
invenio_pidstore/models.py
tests/test_admin.py
tests/test_cli.py
tests/test_ext.py
tests/test_invenio_pidstore.py

cli: initial implementation

---

.editorconfig
invenio_pidstore/admin.py
invenio_pidstore/cli.py
invenio_pidstore/models.py
setup.py
tests/test_invenio_pidstore.py

@lnielsen following `Enum` based solution is the cleanest I could come out with.

models: PIDStatus based on Enum

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

release: v1.0.0a3

---

invenio_pidstore/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

version: post-release bump

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/models.py
invenio_pidstore/version.py

release: v1.0.0a4

---

invenio_pidstore/resolver.py
tests/test_resolver.py

* FIX Fixes issue with resolver not catching errors thrown by the
object getter, which meant that e.g. a deleted record would throw
a NoResultFound error when resolving a deleted PID (used by e.g.
tombstones).

resolver: object getter fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

release: v1.0.0a5

---

.editorconfig
invenio_pidstore/__init__.py
invenio_pidstore/cli.py
invenio_pidstore/ext.py
invenio_pidstore/proxies.py
setup.py

It might be nice for easier use with https://github.com/inveniosoftware/invenio-records/pull/109
--
WDYT @lnielsen ?

global: suffix strip of minter and fetcher name

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

release: v1.0.0a6

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

release: v1.0.0a7

---

babel.ini
docs/conf.py
examples/app.py
invenio_pidstore/__init__.py
invenio_pidstore/admin.py
invenio_pidstore/cli.py
invenio_pidstore/fetchers.py
invenio_pidstore/minters.py
invenio_pidstore/models.py
invenio_pidstore/providers/__init__.py
invenio_pidstore/providers/datacite.py
invenio_pidstore/providers/recordid.py
invenio_pidstore/proxies.py
invenio_pidstore/resolver.py
invenio_pidstore/upgrades/__init__.py
run-tests.sh
setup.cfg
tests/conftest.py
tests/test_admin.py
tests/test_cli.py
tests/test_ext.py
tests/test_fetchers.py
tests/test_minters.py
tests/test_recordidentifier.py
tests/test_resolver.py

global: support for Flask>=0.11

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

release: v1.0.0a9

---

MANIFEST.in
docs/api.rst
examples/app-recreate.sh
examples/app.py
examples/requirements.txt
invenio_pidstore/admin.py
invenio_pidstore/ext.py
invenio_pidstore/fetchers.py
invenio_pidstore/minters.py
invenio_pidstore/models.py
invenio_pidstore/providers/base.py
invenio_pidstore/providers/datacite.py
invenio_pidstore/providers/recordid.py
invenio_pidstore/resolver.py

* Improves documentation. (addresses #75)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

docs: addition of param and result sections

---

invenio_pidstore/providers/base.py

Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

providers: typo fix

---

invenio_pidstore/__init__.py
invenio_pidstore/cli.py
setup.cfg
setup.py
tests/conftest.py
tests/test_cli.py
tests/test_ext.py

* Removed dependency on Flask-CLI.

installation: Flask>=0.11

---

.travis.yml
AUTHORS.rst
MANIFEST.in
babel.ini
docs/api.rst
examples/app.py
examples/requirements.txt
invenio_pidstore/fetchers.py
invenio_pidstore/providers/__init__.py
invenio_pidstore/providers/base.py
invenio_pidstore/providers/datacite.py
invenio_pidstore/providers/recordid.py
invenio_pidstore/upgrades/__init__.py
invenio_pidstore/version.py
setup.py
tests/conftest.py
tests/test_fetchers.py
tests/test_recordidentifier.py

global: preparation for beta release

---

.tx/config
invenio_pidstore/translations/fr/LC_MESSAGES/messages.po
invenio_pidstore/translations/it/LC_MESSAGES/messages.po

i18n: Transifex configuration

---

.travis.yml
invenio_pidstore/translations/cs/LC_MESSAGES/messages.po
invenio_pidstore/translations/de/LC_MESSAGES/messages.po
invenio_pidstore/translations/es/LC_MESSAGES/messages.po
invenio_pidstore/translations/fr/LC_MESSAGES/messages.po
invenio_pidstore/translations/it/LC_MESSAGES/messages.po

Signed-off-by: Alizee Pace <alizee.pace@gmail.com>

i18n: travis fix and translation improvements

---

.travis.yml
examples/app-fixtures.sh
examples/app-setup.sh
examples/app-teardown.sh
examples/app.py
tests/test_examples_app.py

* Adds test_examples_app.py. (closes #86)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

tests: addition of test_examples_app.py

---

MANIFEST.in
docs/requirements.txt

docs: ReadTheDocs configuration

---

RELEASE-NOTES.rst

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docs: move to readthedocs.io

---

docs/conf.py
docs/examplesapp.rst
examples/app.py
invenio_pidstore/alembic/999c62899c20_create_pidstore_tables.py
invenio_pidstore/alembic/f615cee99600_create_pidstore_branch.py

* fix example app rendering problems on readthedocs. (closes #107)
* fix couple of isort-errors
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

docs: fix example app rendering problems on readthedocs

---

.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio_pidstore/translations/cs/LC_MESSAGES/messages.po
invenio_pidstore/translations/da/LC_MESSAGES/messages.po
invenio_pidstore/translations/de/LC_MESSAGES/messages.po
invenio_pidstore/translations/es/LC_MESSAGES/messages.po
invenio_pidstore/translations/fr/LC_MESSAGES/messages.po
invenio_pidstore/translations/it/LC_MESSAGES/messages.po
invenio_pidstore/translations/messages.pot
invenio_pidstore/version.py
setup.py

Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

release: v1.0.0b2

---

setup.py

installation: fix attrs dependency

---

invenio_pidstore/__init__.py
invenio_pidstore/models.py
setup.py

* Closes #122
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

tests: fix build failure caused by docs formating

---

invenio_pidstore/models.py

Fixes exception interpolation for better aggregation handling. 
Using ``format`` exceptions are not grouped correctly by third party aggregators i.e. Sentry.

models: fix exception interpolation for better aggreagation

---

babel.ini
invenio_pidstore/translations/messages.pot
setup.cfg

* remove jinja extensions
* adds fuzzy string true
* update .pot
related inveniosoftware/invenio-app-rdm#1664

i18n: extract messages

---

docs/conf.py
invenio_pidstore/translations/de/LC_MESSAGES/messages.po
setup.py

* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664

i18n: adds german translations

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_pidstore/__init__.py
setup.cfg

- setup: pin dependencies
- setup: change to reusable workflows
- release: v1.3.3

pin dependencies

---

.github/workflows/pypi-publish.yml
CHANGES.rst
invenio_pidstore/__init__.py

- fix: add translation flag for publishing
- release: v1.3.4

fix translations

---

CHANGES.rst
docs/conf.py
invenio_pidstore/__init__.py
setup.cfg

- setup: bump invenio dependencies
- release: v2.0.0

bump major

---

setup.cfg

:heart: Thank you for your contribution!
> Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …

i18n: add Translations Missing Entry Point

---

CHANGES.rst
invenio_pidstore/__init__.py
setup.cfg

:heart: Thank you for your contribution!
> Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …

I18n: Mark Missing Translations Backport

---

CHANGES.rst
invenio_pidstore/__init__.py
invenio_pidstore/cli.py

- **fix(wording): fix wording of cli create option validation**
- **release: v2.2.1**

cli create wording
